version: "3"

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db
      - redis

  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - app

  db:
    build: .docker/mysql
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    command: --innodb-use-native-aio=0
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=a1s2d3f4
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# kubectl apply -f k8s/app
# kubectl apply -f k8s/mysql
# kubectl apply -f k8s/nginx
# kubectl apply -f k8s/redis
# git push origin master
# kubectl get pods
# kubectl exec -it app-558bd8887b-p7lfv bash
# mysql -uroot -hmysql-service -p     # a1s2d3f4