version: "3"

services:
  app:
    build: .
    container_name: app
    entrypoint: dockerize -template ./.docker/app/.envTemplate:.env -template ./.docker/nginx/nginxTemplate.conf:./.docker/nginx/nginx.conf -wait tcp://db:3306 -timeout 40s ./.docker/app/entrypoint.sh
    environment:
      - _DB_HOST=db
      - _DB_DATABASE=laravel
      - _DB_USERNAME=root
      - _DB_PASSWORD=a1s2d3f4
      - _HOST=app
      - _PORTA=9000
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db
      - redis

  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - app

  db:
    build: .docker/mysql
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    command: --innodb-use-native-aio=0
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=a1s2d3f4
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# docker-compose up -d
# docker-compose up -d --build
# docker exec -u root -it app bash