apiVersion: v1
kind: Service
metadata:
    name: mysql-service
    labels:
      app: mysql-service
spec:
    ports:
      - port: 3306
    selector:
      app: mysql-deployment
      tier: db
    clusterIP: None